export {default as AddGame} from 'game/addGame'
export {default as AddTeam} from 'game/addTeam'
export {default as GetGames} from 'game/getGames'
export {default as GetTeams} from 'game/getTeams'
export {default as ModifyGame} from 'game/modifyGame'
export {default as ModifyTeam} from 'game/modifyTeam'
export {default as RemoveGame} from 'game/removeGame'
export {default as RemoveTeam} from 'game/removeTeam'