export {default as Bmi} from 'basic/bmi'
export {default as Calc} from 'basic/calc'
export {default as Counter} from 'basic/counter'
export {default as Grade} from 'basic/grade'
export {default as BasicNav} from 'basic/basic-nav'
export {default as BasicLayout} from 'basic/basic-layout'